## Unit 2 - Subsetting DataFrames and Series

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/airbnb_input.csv', index_col='room_id')

On df DataFrame you can find data about Airbnb rooms in Lisbon.

Go ahead and preview it!

In [3]:
# code to preview df
df

host_id        room_type             neighborhood  reviews  \
room_id                                                                  
6499          14455  Entire home/apt                    Belém        8   
17031         66015  Entire home/apt                 Alvalade        0   
25659        107347  Entire home/apt        Santa Maria Maior       63   
29248        125768  Entire home/apt        Santa Maria Maior      225   
29396        126415  Entire home/apt        Santa Maria Maior      132   
29720        128075  Entire home/apt                  Estrela       14   
29872        128698  Entire home/apt                Alcântara       25   
29891        128792  Entire home/apt             Misericórdia       28   
29915        128890  Entire home/apt           Avenidas Novas       28   
33312        144398  Entire home/apt             Misericórdia       24   
33348        144484     Private room                   Lumiar        2   
34783        149980     Private room                  Estrela        0   
34977        146695  Entire home/apt        Santa Maria Maior       54   
40817        176410  Entire home/apt             Misericórdia      229   
42172        184400  Entire home/apt        Santa Maria Maior       45   
42519        136230  Entire home/apt             Misericórdia       79   
44043        192830  Entire home/apt        Santa Maria Maior      316   
46567        208343     Private room           Avenidas Novas        3   
47717        217058  Entire home/apt        Santa Maria Maior       70   
50108        229376  Entire home/apt                  Estrela       33   
55116        259744     Private room           Avenidas Novas        1   
56906        270457  Entire home/apt              São Vicente       86   
57850        276092  Entire home/apt                  Estrela       52   
59227        184400  Entire home/apt             Misericórdia       25   
65553        320407  Entire home/apt         Campo de Ourique      102   
65878        322145  Entire home/apt             Misericórdia       51   
72807        378525     Private room                 Alvalade        1   
73764        154341  Entire home/apt            Santo António       18   
75171        184400  Entire home/apt                  Estrela       19   
77130        412702  Entire home/apt             Misericórdia       74   
...             ...              ...                      ...      ...   
19360001   26864642     Private room                  Arroios        0   
19361749  127589264  Entire home/apt  São Domingos de Benfica        0   
19362076   88928860  Entire home/apt          Penha de França        0   
19362417   28225140     Private room                  Arroios        0   
19363100   88928860     Private room          Penha de França        0   
19368183   14317794  Entire home/apt             Misericórdia        0   
19369538  114388582  Entire home/apt             Misericórdia        0   
19370050   14317794  Entire home/apt             Misericórdia        0   
19370165  114388582  Entire home/apt            Santo António        0   
19370278  135784989  Entire home/apt        Santa Maria Maior        0   
19370578  131185696  Entire home/apt                Alcântara        0   
19370769  135787783  Entire home/apt        Santa Maria Maior        0   
19373212  131185696  Entire home/apt                Alcântara        0   
19376122  119457178  Entire home/apt                    Ajuda        0   
19379554  104083974  Entire home/apt                    Belém        0   
19379856   12723358  Entire home/apt        Parque das Nações        0   
19380177  104083974  Entire home/apt                    Belém        0   
19380414   85047832  Entire home/apt              São Vicente        0   
19380457  104083974  Entire home/apt                    Belém        0   
19381136  131185696  Entire home/apt                Alcântara        0   
19383103   48844725  Entire home/apt                  Estrela        0   
19383615  100924

## Row selection

### Selecting rows by index position - iloc

* With function [iloc](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.iloc.html) you can select specific rows from a DataFrame.
* In order to specify the rows you want to select you can use, for instance, the row position (integer starting from 0) or a list of row positions.

Here, we are selecting the first row and getting it as a pandas Series:

In [4]:
df.iloc[0]

host_id                           14455
room_type               Entire home/apt
neighborhood                      Belém
reviews                               8
overall_satisfaction                  5
accommodates                          2
bedrooms                              1
price                                57
Name: 6499, dtype: object

But you can also get a single row as a DataFrame:

In [5]:
df.iloc[[0]]

host_id        room_type neighborhood  reviews  overall_satisfaction  \
room_id                                                                         
6499       14455  Entire home/apt        Belém        8                   5.0   

         accommodates  bedrooms  price  
room_id                                 
6499                2       1.0   57.0

Now try to get rows 0, 1 and 3, using iloc:

In [ ]:
# code to select rows 0, 1 and 3 from df

Array slices also work, so try to select all the rows from position number 2 to position number 7:

In [ ]:
# code to select rows [2, 7] from df

### Selecting rows by index name - loc

* With function [loc](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.loc.html) you can select specific rows from a DataFrame, like with iloc.
* The difference here is that you specify the rows to select using the rows' indexes.

Here, we're selecting the row that corresponds to room 17031 (with index 17031):

In [ ]:
df.loc[17031]

Now, if you select a row for an index that doesn't exist you'll get a KeyError:

In [ ]:
df.loc[[1]]

Try to select the rows that correspond to rooms 17031 and 25659:

In [ ]:
# code to select rooms 17031 and 25659

Now check what happens when you pass a boolean array to loc!

In [ ]:
# code to call loc with a boolean array

## Column selection

### Selecting columns by name - dot, brackets

You can select columns using dot notation, like this:

In [ ]:
df.room_type

Or using brackets, like this:

In [ ]:
df['room_type']

Now, try to select column room_type from df, but getting the result as a DataFrame instead of a Series:

In [ ]:
# code to get column room_type from df as a DataFrame

And now try to select columns room_type and neighborhood:

In [ ]:
# code to select columns room_type and neighborhood

If you're feeling confident, here's a little challenge: select column room_type using loc!

In [ ]:
# code to select column room_type using loc

## Mask function

[Mask](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.mask.html) function can be used to "hide" the rows that verify a certain condition:

In [ ]:
df.mask(df.overall_satisfaction == 5.0)

## Where function

And with [where](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.where.html) function, you can hide the rows that __don't__ verify a certain condition:

In [ ]:
df.where(df.overall_satisfaction == 5.0)

## Filter data

* You can also use conditions inside brackets to filter data from the DataFrame
* When you do it you get a DataFrame that has a different shape from the initial one
* While with mask/filter, the DataFame shape is the same, and you just get NaNs in the cells that verify/don't verify the conditions

Here we're selecting only the rows of rooms in the Alvalade neighborhood:

In [ ]:
df[df.neighborhood == 'Alvalade']

## Selection based on data types

Check DataFrame's data types by using the class attribute dtypes:

In [ ]:
df.dtypes

In order to select columns based on their data type, use the function select_dtypes:

In [ ]:
df.select_dtypes(include=['float64'])

## Writing data to files

To output your processed data to a file, pandas has many function to help you with that:
* [to_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html)
* [to_json](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html)
* [to_excel](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_excel.html)

Check more [here](https://pandas.pydata.org/pandas-docs/stable/io.html) !

Here, we're exporting df to a csv file called airbnb_output.csv on the data directory of this unit:

In [ ]:
df.to_csv('../data/airbnb_output.csv')