nshow <- read_csv("C:/Users/Francisco/Dropbox/IST-MEIC/2ºano/1ºsemestre/SAD/Projecto/noshows.csv")
nsData = nshow[, 6:13]
nsData$Neighbourhood <- NULL
View(nsData)
pca1ns <- princomp(nsData, cor=TRUE)
summary(pca1ns)
nsData2 <- data.frame(scale(nsData))
pcaFns <- prcomp(nsData2)
PCAcomps <- data.frame(pcaFns$x[,1:5])
plot(PCAcomps, pch=25)
probClusters <- (nrow(nsData)-1)*sum(apply(nsData,2,var))
for (i in 2:15) probClusters[i] <- sum(kmeans(nsData, centers=i)$withinss)
plot(1:15, probClusters, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
clusterNS <- kmeans(PCAcomps, 4, nstart=20, iter.max=2000)
View(clusterNS)
library(RColorBrewer)
library(scales)
palette(alpha(brewer.pal(9,'Set1'), 0.5))
plot(PCAcomps, col=clusterNS$clust, pch=25)
plot(PCAcomps, aes(PC1, PC2, col=clusterNS$cluster))